export const LOAD_INGREDIENT = "LOAD_INGREDIENT",
  GET_INGREDIENT_SUCCESS = "GET_INGREDIENT_SUCCESS",
  CLEAR_INGREDIENT = "CLEAR_INGREDIENT",
  SET_CONVERSION_INPUT_VALUES = "SET_CONVERSION_INPUT_VALUES",
  CLEAR_CONVERSION_INPUT_VALUES = "CLEAR_CONVERSION_INPUT_VALUES",
  SET_CONVERSION_TYPE = "SET_CONVERSION_TYPE",
  SET_SEARCH_INPUT_VALUE = "SET_SEARCH_INPUT_VALUE";
