export const LOAD_INGREDIENT = "LOAD_INGREDIENT",
  GET_INGREDIENT_SUCCESS = "GET_INGREDIENT_SUCCESS",
  CLEAR_INGREDIENT = "CLEAR_INGREDIENT",
  SET_CONVERSION_INPUT_VALUES = "SET_CONVERSION_INPUT_VALUES",
  CLEAR_CONVERSION_INPUT_VALUES = "CLEAR_CONVERSION_INPUT_VALUES",
  SET_CONVERSTION_TYPE = "SET_CONVERSTION_TYPE";
